#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <limits>
#include <vector>

#include "quixicore_cpu/qgemv.h"

#define REQUIRE(condition)                                                \
  do {                                                                    \
    if (!(condition)) {                                                   \
      std::cerr << "FAILED: " #condition " at " << __FILE__ << ":"      \
                << __LINE__ << '\n';                                      \
      return 1;                                                           \
    }                                                                     \
  } while (0)

namespace {

std::uint64_t fnv1a(const std::vector<std::uint8_t>& bytes) {
  std::uint64_t hash = 14695981039346656037ULL;
  for (std::uint8_t byte : bytes) {
    hash ^= byte;
    hash *= 1099511628211ULL;
  }
  return hash;
}

}  // namespace

int main() {
  using namespace quixicore_cpu;
  struct Fixture {
    QuantActivationFormat format;
    long long block;
    std::size_t bytes;
  };
  const Fixture fixtures[] = {
      {QuantActivationFormat::kQ8_0, 32, 34},
      {QuantActivationFormat::kQ8_1, 32, 36},
      {QuantActivationFormat::kQ8_K, 256, 292},
  };

  for (const Fixture& fixture : fixtures) {
    std::size_t bytes = 0;
    REQUIRE(quant_activation_packed_size(fixture.format, 2, fixture.block,
                                         &bytes) == Status::kOk);
    REQUIRE(bytes == 2 * fixture.bytes);
    std::vector<float> input(static_cast<std::size_t>(2 * fixture.block));
    for (std::size_t i = 0; i < input.size(); ++i) {
      input[i] = static_cast<float>((i * 37) % 257) / 91.0f - 1.4f;
    }
    std::vector<std::uint8_t> packed(bytes, 0);
    REQUIRE(quant_activation_pack(fixture.format, input.data(), 2,
                                  fixture.block, packed.data()) ==
            Status::kOk);
    std::vector<float> unpacked(input.size());
    REQUIRE(quant_activation_unpack(fixture.format, packed.data(), 2,
                                    fixture.block, unpacked.data()) ==
            Status::kOk);
    float maximum = 0.0f;
    for (std::size_t i = 0; i < input.size(); ++i) {
      maximum = std::max(maximum, std::fabs(input[i] - unpacked[i]));
    }
    REQUIRE(maximum < 0.025f);

    std::vector<float> bad(static_cast<std::size_t>(fixture.block), 0.0f);
    bad[3] = std::numeric_limits<float>::infinity();
    REQUIRE(quant_activation_pack(fixture.format, bad.data(), 1,
                                  fixture.block, packed.data()) ==
            Status::kInvalidArgument);
  }

  REQUIRE(quant_activation_packed_size(QuantActivationFormat::kQ8_1, 1, 31,
                                       nullptr) == Status::kInvalidShape);
  std::size_t bytes = 0;
  REQUIRE(quant_activation_packed_size(QuantActivationFormat::kQ8_K, 1, 256,
                                       &bytes) == Status::kOk);
  REQUIRE(bytes == 292);

  // Stable canonical hashes generated by llama.cpp 2beefef68's reference
  // quantizers for the deterministic corpus below.
  std::vector<float> corpus(256);
  for (std::size_t i = 0; i < corpus.size(); ++i) {
    corpus[i] = static_cast<float>(static_cast<int>((i * 37) % 257) - 128) /
                    91.0f +
                static_cast<float>(static_cast<int>(i % 7) - 3) / 256.0f;
  }
  const std::uint64_t golden_hashes[] = {
      0x63b041b789cfb80dULL,
      0x14d79eb59f0489edULL,
      0x3828c2e0137c6b2eULL,
  };
  std::size_t fixture_index = 0;
  for (const Fixture& fixture : fixtures) {
    std::size_t corpus_bytes = 0;
    REQUIRE(quant_activation_packed_size(fixture.format, 1, fixture.block,
                                         &corpus_bytes) == Status::kOk);
    std::vector<std::uint8_t> packed(corpus_bytes, 0);
    REQUIRE(quant_activation_pack(fixture.format, corpus.data(), 1,
                                  fixture.block, packed.data()) ==
            Status::kOk);
    REQUIRE(fnv1a(packed) == golden_hashes[fixture_index]);
    ++fixture_index;
  }

  // Contract route: compare to the same packed activation explicitly
  // dequantized and passed through the f32-activation GEMV.
  constexpr long long kN = 5;
  constexpr long long kK = 256;
  std::vector<float> weights(kN * kK);
  for (std::size_t i = 0; i < weights.size(); ++i) {
    weights[i] = std::sin(static_cast<float>(i) * 0.013f);
  }
  std::size_t weight_bytes = 0;
  REQUIRE(qgemv_packed_size(QuantFormat::kQ4_K, kN, kK, &weight_bytes) ==
          Status::kOk);
  std::vector<std::uint8_t> packed_weights(weight_bytes);
  REQUIRE(qgemv_pack(QuantFormat::kQ4_K, weights.data(), kN, kK,
                     packed_weights.data()) == Status::kOk);
  REQUIRE(quant_activation_packed_size(QuantActivationFormat::kQ8_K, 1, kK,
                                       &bytes) == Status::kOk);
  std::vector<std::uint8_t> packed_activation(bytes);
  REQUIRE(quant_activation_pack(QuantActivationFormat::kQ8_K, corpus.data(), 1,
                                kK, packed_activation.data()) == Status::kOk);
  std::vector<float> dequantized(kK), expected(kN), actual(kN);
  REQUIRE(quant_activation_unpack(QuantActivationFormat::kQ8_K,
                                  packed_activation.data(), 1, kK,
                                  dequantized.data()) == Status::kOk);
  REQUIRE(qgemv(QuantFormat::kQ4_K, packed_weights.data(), dequantized.data(),
                expected.data(), kN, kK) == Status::kOk);
  REQUIRE(qgemv_quantized_activation(
              QuantFormat::kQ4_K, packed_weights.data(),
              QuantActivationFormat::kQ8_K, packed_activation.data(),
              actual.data(), kN, kK) == Status::kOk);
  for (long long i = 0; i < kN; ++i) REQUIRE(actual[i] == expected[i]);

  return 0;
}
